name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v3.0.0
      with:
        node-version: lts/*
    - run: sudo apt-get install libgbm1
    - run: npm install
    - run: npm test
      env:
        CI: true
